// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog/blog.proto

package com.test.blog.protofiles;

public interface CreateBlogResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.CreateBlogResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * el id lo regresara mongo
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   * @return Whether the blog field is set.
   */
  boolean hasBlog();
  /**
   * <pre>
   * el id lo regresara mongo
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   * @return The blog.
   */
  com.test.blog.protofiles.Blog getBlog();
  /**
   * <pre>
   * el id lo regresara mongo
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   */
  com.test.blog.protofiles.BlogOrBuilder getBlogOrBuilder();
}
